# Generated by Django 2.2.3 on 2019-08-11 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='sfile',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'aac'])]),
        ),
    ]
