# Generated by Django 2.2.3 on 2019-08-23 16:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('gaana', '0002_auto_20190811_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(default='settings.MEDIA_ROOT/def.jpg', upload_to='')),
                ('DOB', models.DateField(default=datetime.datetime(2019, 8, 23, 22, 18, 6, 472849))),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
