# Generated by Django 2.2.3 on 2019-08-26 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0005_auto_20190826_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipphoto',
            name='voice_record',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 12, 4, 12, 636357)),
        ),
    ]
